[versions]
agp = "8.13.1"
coreSplashscreen = "1.2.0"
hiltNavigationCompose = "1.3.0"
kotlin = "2.2.21"
hilt = "2.57.2"
credentials = "1.5.0"
googleid = "1.1.1"

# Compose UI + Material3
#
compose = "1.10.0"
material= "1.4.0"
composeCompiler = "1.5.3"

# Base AndroidX
#
coreKtx = "1.17.0"
activityCompose = "1.12.1"
lifecycle = "2.10.0"
materialVersion = "1.13.0"
navigation = "2.9.6"

# Test
#
junit = "4.13.2"
androidxJunit = "1.3.0"
browser = "1.9.0"
retrofitBom = "3.0.0"

[libraries]
#Base
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
# Hilt
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltNavigationCompose" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
# Compose core
#
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
# Material 3
#
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material" }
androidx-material3-icons = { group = "androidx.compose.material", name = "material-icons-core", version = "1.7.8"}
androidx-material3-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.7.8"}
# Activity con soporte Compose
#
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
# Lifecycle + ViewModel + Navigation
#
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
# Hilt
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
# Testing (Compose)
#
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
# Unit / Instrumented tests base
#
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
# Google SSO
#
credentials-core = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
credentials-play-services = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentials" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }
retrofit = { module = "com.squareup.retrofit2:retrofit" }
retrofit-bom = { module = "com.squareup.retrofit2:retrofit-bom", version.ref = "retrofitBom" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]
credentials-google = [
    "credentials-core",
    "credentials-play-services",
    "googleid",
]
